create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text unique not null,
    display_name text,
    points integer not null default 0,
    approved boolean not null default false,
    is_admin boolean not null default false,
    created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists points integer not null default 0;
alter table public.profiles add column if not exists approved boolean not null default false;
alter table public.profiles add column if not exists is_admin boolean not null default false;
alter table public.profiles add column if not exists created_at timestamptz not null default now();

create table if not exists public.links (
    id bigint generated by default as identity primary key,
    title text not null,
    url text not null,
    description text not null default '',
    tag text not null default 'link',
    sort_order integer not null default 0,
    created_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now()
);

alter table public.links add column if not exists description text not null default '';
alter table public.links add column if not exists tag text not null default 'link';
alter table public.links add column if not exists sort_order integer not null default 0;
alter table public.links add column if not exists created_by uuid references public.profiles(id) on delete set null;
alter table public.links add column if not exists created_at timestamptz not null default now();

create table if not exists public.announcements (
    id bigint generated by default as identity primary key,
    title text not null,
    body text not null,
    created_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now()
);

alter table public.announcements add column if not exists created_by uuid references public.profiles(id) on delete set null;
alter table public.announcements add column if not exists created_at timestamptz not null default now();

create table if not exists public.challenges (
    id bigint generated by default as identity primary key,
    title text not null,
    summary text not null,
    details text not null,
    points integer not null default 0,
    status text not null default 'open' check (status in ('open', 'archived')),
    created_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now()
);

alter table public.challenges add column if not exists summary text not null default '';
alter table public.challenges add column if not exists details text not null default '';
alter table public.challenges add column if not exists points integer not null default 0;
alter table public.challenges add column if not exists status text not null default 'open';
alter table public.challenges add column if not exists created_by uuid references public.profiles(id) on delete set null;
alter table public.challenges add column if not exists created_at timestamptz not null default now();

create table if not exists public.challenge_acceptances (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    challenge_id bigint not null references public.challenges(id) on delete cascade,
    status text not null default 'accepted' check (status in ('accepted', 'completed')),
    created_at timestamptz not null default now(),
    completed_at timestamptz,
    unique(user_id, challenge_id)
);

alter table public.challenge_acceptances add column if not exists status text not null default 'accepted';
alter table public.challenge_acceptances add column if not exists created_at timestamptz not null default now();
alter table public.challenge_acceptances add column if not exists completed_at timestamptz;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, email, display_name, approved, is_admin)
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)),
        case when new.email = 'dawid.232.v2@gmail.com' then true else false end,
        case when new.email = 'dawid.232.v2@gmail.com' then true else false end
    )
    on conflict (id) do nothing;

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.links enable row level security;
alter table public.announcements enable row level security;
alter table public.challenges enable row level security;
alter table public.challenge_acceptances enable row level security;

drop policy if exists "profiles self read" on public.profiles;
create policy "profiles self read"
on public.profiles for select
to authenticated
using (
    auth.uid() = id
    or exists (
        select 1
        from public.profiles admin_profile
        where admin_profile.id = auth.uid()
          and admin_profile.is_admin = true
          and admin_profile.approved = true
    )
);

drop policy if exists "profiles self update" on public.profiles;
create policy "profiles self update"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (
    auth.uid() = id
    and is_admin = is_admin
    and approved = approved
    and points = points
);

drop policy if exists "profiles admin update" on public.profiles;
create policy "profiles admin update"
on public.profiles for update
to authenticated
using (
    exists (
        select 1
        from public.profiles admin_profile
        where admin_profile.id = auth.uid()
          and admin_profile.is_admin = true
          and admin_profile.approved = true
    )
)
with check (
    exists (
        select 1
        from public.profiles admin_profile
        where admin_profile.id = auth.uid()
          and admin_profile.is_admin = true
          and admin_profile.approved = true
    )
);

drop policy if exists "public read links" on public.links;
create policy "public read links"
on public.links for select
to anon, authenticated
using (true);

drop policy if exists "admins manage links" on public.links;
create policy "admins manage links"
on public.links for all
to authenticated
using (
    exists (
        select 1
        from public.profiles admin_profile
        where admin_profile.id = auth.uid()
          and admin_profile.is_admin = true
          and admin_profile.approved = true
    )
)
with check (
    exists (
        select 1
        from public.profiles admin_profile
        where admin_profile.id = auth.uid()
          and admin_profile.is_admin = true
          and admin_profile.approved = true
    )
);

drop policy if exists "public read announcements" on public.announcements;
create policy "public read announcements"
on public.announcements for select
to anon, authenticated
using (true);

drop policy if exists "admins manage announcements" on public.announcements;
create policy "admins manage announcements"
on public.announcements for all
to authenticated
using (
    exists (
        select 1
        from public.profiles admin_profile
        where admin_profile.id = auth.uid()
          and admin_profile.is_admin = true
          and admin_profile.approved = true
    )
)
with check (
    exists (
        select 1
        from public.profiles admin_profile
        where admin_profile.id = auth.uid()
          and admin_profile.is_admin = true
          and admin_profile.approved = true
    )
);

drop policy if exists "public read challenges" on public.challenges;
create policy "public read challenges"
on public.challenges for select
to anon, authenticated
using (true);

drop policy if exists "admins manage challenges" on public.challenges;
create policy "admins manage challenges"
on public.challenges for all
to authenticated
using (
    exists (
        select 1
        from public.profiles admin_profile
        where admin_profile.id = auth.uid()
          and admin_profile.is_admin = true
          and admin_profile.approved = true
    )
)
with check (
    exists (
        select 1
        from public.profiles admin_profile
        where admin_profile.id = auth.uid()
          and admin_profile.is_admin = true
          and admin_profile.approved = true
    )
);

drop policy if exists "users read own acceptances" on public.challenge_acceptances;
create policy "users read own acceptances"
on public.challenge_acceptances for select
to authenticated
using (
    user_id = auth.uid()
    or exists (
        select 1
        from public.profiles admin_profile
        where admin_profile.id = auth.uid()
          and admin_profile.is_admin = true
          and admin_profile.approved = true
    )
);

drop policy if exists "approved users accept challenges" on public.challenge_acceptances;
create policy "approved users accept challenges"
on public.challenge_acceptances for insert
to authenticated
with check (
    user_id = auth.uid()
    and exists (
        select 1
        from public.profiles own_profile
        where own_profile.id = auth.uid()
          and own_profile.approved = true
    )
);

drop policy if exists "approved users complete own challenges" on public.challenge_acceptances;
create policy "approved users complete own challenges"
on public.challenge_acceptances for update
to authenticated
using (
    user_id = auth.uid()
    and exists (
        select 1
        from public.profiles own_profile
        where own_profile.id = auth.uid()
          and own_profile.approved = true
    )
)
with check (
    user_id = auth.uid()
    and exists (
        select 1
        from public.profiles own_profile
        where own_profile.id = auth.uid()
          and own_profile.approved = true
    )
);

insert into public.links (title, url, description, tag, sort_order)
values
    ('Main Website', 'https://example.com', 'Primary destination for users.', 'external', 1),
    ('Documentation', 'https://example.com/docs', 'Rules, notes, or reference material.', 'guide', 2)
on conflict do nothing;

insert into public.announcements (title, body)
values
    ('Welcome', 'Announcements appear here for the whole squad.')
on conflict do nothing;

insert into public.challenges (title, summary, details, points, status)
values
    ('Launch Check', 'Verify the main page loads correctly.', 'Open the main page, confirm the hero renders, and report any issues.', 10, 'open'),
    ('Mobile Audit', 'Review spacing and contrast on mobile.', 'Check the page on a narrow screen and note any readability or spacing problems.', 15, 'open')
on conflict do nothing;
